package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/spf13/cobra"
)

var (
	flagServer string
	flagToken  string
	flagImage  string
)

// resolveSetting returns the first non-empty of: explicit flag, environment,
// ~/.config/mygrok/env (KEY=VALUE lines).
func resolveSetting(flagVal, envKey string) string {
	if flagVal != "" {
		return flagVal
	}
	if v := os.Getenv(envKey); v != "" {
		return v
	}
	if home, err := os.UserHomeDir(); err == nil {
		data, err := os.ReadFile(filepath.Join(home, ".config", "mygrok", "env"))
		if err == nil {
			sc := bufio.NewScanner(strings.NewReader(string(data)))
			for sc.Scan() {
				k, v, ok := strings.Cut(sc.Text(), "=")
				if ok && strings.TrimSpace(k) == envKey {
					return strings.TrimSpace(v)
				}
			}
		}
	}
	return ""
}

func requireServerToken() (string, string) {
	server := resolveSetting(flagServer, "MYGROK_SERVER")
	token := resolveSetting(flagToken, "MYGROK_TOKEN")
	if server == "" || token == "" {
		fmt.Fprintln(os.Stderr, "ERROR: MYGROK_SERVER / MYGROK_TOKEN not set.")
		fmt.Fprintln(os.Stderr, "Set them in the environment or in ~/.config/mygrok/env, e.g.:")
		fmt.Fprintln(os.Stderr, "  MYGROK_SERVER=your-vps.com:7000")
		fmt.Fprintln(os.Stderr, "  MYGROK_TOKEN=your-secret-token")
		os.Exit(1)
	}
	return server, token
}

func imageTag() string {
	if tag := resolveSetting(flagImage, "MYGROK_TAG"); tag != "" {
		return tag
	}
	return "latest"
}

// buildCommandArgs assembles the mygrok client CLI args for a tunnel.
func buildCommandArgs(proto, port, sub, localHost string, publicPort int) []string {
	args := []string{
		"mygrok", proto, port, sub,
		"--server", "${MYGROK_SERVER}",
		"--no-tui", "--log-format", "json",
		"--local-host", localHost,
	}
	if proto == "https" {
		args = append(args, "--insecure")
	}
	if publicPort > 0 {
		args = append(args, "--public-port", strconv.Itoa(publicPort))
	}
	return args
}

// envFileContent is the <dir>/mygrok/.env body (written with mode 0600).
func envFileContent(server, token, tag string) string {
	return fmt.Sprintf("# Generated by mygrok task -- safe to edit.\nMYGROK_SERVER=%s\nMYGROK_TOKEN=%s\nMYGROK_TAG=%s\n", server, token, tag)
}

var addCmd = &cobra.Command{
	Use:   "add <dir> --port <n> --sub <name>",
	Short: "Scaffold <dir>/mygrok/ with a docker-compose tunnel config",
	Long: `Scaffold a per-project mygrok tunnel: creates <dir>/mygrok/docker-compose.yml
(one tunnel = one container) and <dir>/mygrok/.env (server address + token,
mode 0600).

With --multi, one container runs every tunnel added to the directory:
<dir>/mygrok/tunnels.json collects the tunnel specs and each later
"add --multi" appends another entry to it.

Examples:
  task add ~/dev/myapp --port 3000 --sub my-app
  task add ~/dev/mygame --port 8123 --sub mygame --network proxy --local-host mygame
  task add ~/dev/mybox --proto tcp --port 22 --sub ssh --public-port 2222
  task add --multi ~/dev/mybox --port 3000 --sub api
  task add --multi ~/dev/mybox --proto tcp --port 22 --sub ssh --public-port 2222`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		dir, err := filepath.Abs(args[0])
		if err != nil || !isDir(dir) {
			return fmt.Errorf("directory not found: %s", args[0])
		}
		server, token := requireServerToken()
		tag := imageTag()

		port, _ := cmd.Flags().GetInt("port")
		sub, _ := cmd.Flags().GetString("sub")
		proto, _ := cmd.Flags().GetString("proto")
		localHost, _ := cmd.Flags().GetString("local-host")
		network, _ := cmd.Flags().GetString("network")
		publicPort, _ := cmd.Flags().GetInt("public-port")
		multi, _ := cmd.Flags().GetBool("multi")

		if multi {
			return runMultiAdd(multiAddParams{
				dir: dir, sub: sub, proto: proto, port: port,
				localHost: localHost, network: network, publicPort: publicPort,
				server: server, token: token, tag: tag,
			})
		}

		if port <= 0 {
			return fmt.Errorf("--port is required")
		}
		if !isValidLabel(sub) {
			return fmt.Errorf("--sub must be a lowercase dns label (letters, digits, hyphens), got %q", sub)
		}
		if proto != "http" && proto != "https" && proto != "tcp" && proto != "udp" {
			return fmt.Errorf("--proto must be http|https|tcp|udp")
		}
		if network != "" && localHost == "127.0.0.1" {
			return fmt.Errorf("--network requires --local-host (the target container/service name on that network)")
		}

		mygrokDir := filepath.Join(dir, "mygrok")
		composePath := filepath.Join(mygrokDir, "docker-compose.yml")
		if err := guardSingleAdd(mygrokDir); err != nil {
			return err
		}
		if _, err := os.Stat(composePath); err == nil {
			return fmt.Errorf("%s already exists (refusing to overwrite; edit it or remove the folder)", composePath)
		}
		if err := os.MkdirAll(mygrokDir, 0o755); err != nil {
			return err
		}

		envContent := envFileContent(server, token, tag)
		if err := os.WriteFile(filepath.Join(mygrokDir, ".env"), []byte(envContent), 0o600); err != nil {
			return err
		}

		cmdArgs := buildCommandArgs(proto, strconv.Itoa(port), sub, localHost, publicPort)
		var b strings.Builder
		b.WriteString("[")
		for i, a := range cmdArgs {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(`"` + a + `"`)
		}
		b.WriteString("]")

		var netBlock string
		if network != "" {
			netBlock = fmt.Sprintf("    networks:\n      - %s\n    restart: unless-stopped\n\nnetworks:\n  %s:\n    external: true\n", network, network)
		} else {
			netBlock = "    network_mode: host\n    restart: unless-stopped\n"
		}

		compose := fmt.Sprintf(`# Generated by mygrok task -- safe to edit.
# One tunnel = one container. Logs: docker compose -f %s logs -f
name: mygrok-%s

services:
  %s:
    image: mygrok:${MYGROK_TAG:-%s}
    container_name: mygrok_%s
    command: %s
    environment:
      MYGROK_TOKEN: ${MYGROK_TOKEN}
%s`, composePath, sub, sub, tag, sub, b.String(), netBlock)

		if err := os.WriteFile(composePath, []byte(compose), 0o644); err != nil {
			return err
		}
		fmt.Printf("Created %s/{docker-compose.yml,.env}\n", mygrokDir)
		fmt.Printf("Start:  mygrok-task up %s\n", dir)
		return nil
	},
}

func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

// --- multi-tunnel mode: one container runs every tunnel in tunnels.json ---

// multiTunnelSpec mirrors one "tunnels" entry of the client's profile config
// (cmd/client). It stays a strict subset of the client's TunnelSpec fields;
// the client ignores unknown keys, so this file shape always loads.
type multiTunnelSpec struct {
	Name       string `json:"name"`
	Protocol   string `json:"protocol"`
	Port       int    `json:"port"`
	Subdomain  string `json:"subdomain"`
	PublicPort int    `json:"public_port,omitempty"`
	LocalHost  string `json:"local_host,omitempty"`
}

// multiConfig is the JSON document written to <dir>/mygrok/tunnels.json.
// server/token stay empty on purpose: the container environment
// (MYGROK_SERVER / MYGROK_TOKEN) supplies them, so no secret ever lands in
// the (committed) tunnels.json file.
type multiConfig struct {
	Server  string            `json:"server"`
	Token   string            `json:"token"`
	Tunnels []multiTunnelSpec `json:"tunnels"`
}

type multiAddParams struct {
	dir        string
	sub        string
	proto      string
	port       int
	localHost  string
	network    string
	publicPort int
	server     string
	token      string
	tag        string
}

// sanitizeLabel reduces s to a valid lowercase DNS-1123 label (letters,
// digits, hyphens; no leading/trailing hyphen; at most 63 chars) for use as
// a compose project name / container name, matching the label charset that
// --sub is validated against in single mode.
func sanitizeLabel(s string) string {
	var b strings.Builder
	pending := false
	for _, r := range strings.ToLower(s) {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			if pending {
				b.WriteByte('-')
				pending = false
			}
			b.WriteRune(r)
		default:
			pending = true
		}
	}
	label := strings.Trim(b.String(), "-")
	if len(label) > 63 {
		label = strings.Trim(label[:63], "-")
	}
	if label == "" {
		label = "app"
	}
	return label
}

// guardSingleAdd refuses to scaffold a single-tunnel dir that is already a
// multi-mode dir (has tunnels.json).
func guardSingleAdd(mygrokDir string) error {
	if p := filepath.Join(mygrokDir, "tunnels.json"); fileExists(p) {
		return fmt.Errorf("%s is a multi-tunnel directory (tunnels.json present) -- use: mygrok-task add --multi <dir> --port <n> --sub <name>", p)
	}
	return nil
}

// guardMultiAdd refuses to scaffold a multi-tunnel dir that is a
// single-mode dir (has docker-compose.yml but no tunnels.json).
func guardMultiAdd(mygrokDir string) error {
	composePath := filepath.Join(mygrokDir, "docker-compose.yml")
	if fileExists(composePath) && !fileExists(filepath.Join(mygrokDir, "tunnels.json")) {
		return fmt.Errorf("%s is a single-tunnel directory (no tunnels.json) -- pick another directory or remove %s", composePath, mygrokDir)
	}
	return nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// loadMultiConfig reads tunnels.json; a missing file yields an empty config.
func loadMultiConfig(path string) (*multiConfig, error) {
	cfg := &multiConfig{Tunnels: []multiTunnelSpec{}}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return nil, err
	}
	if err := json.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return cfg, nil
}

// saveMultiConfig writes tunnels.json (mode 0644 -- it holds no secrets).
func saveMultiConfig(path string, cfg *multiConfig) error {
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

// multiComposeYAML renders the one-container multi-tunnel compose file: a
// single `mygrok` service running `mygrok up --config /etc/mygrok/tunnels.json`
// with the file mounted read-only; server/token come from the environment.
func multiComposeYAML(composePath, name, tag, network string) string {
	var netBlock string
	if network != "" {
		netBlock = fmt.Sprintf("    networks:\n      - %s\n    restart: unless-stopped\n\nnetworks:\n  %s:\n    external: true\n", network, network)
	} else {
		netBlock = "    network_mode: host\n    restart: unless-stopped\n"
	}
	return fmt.Sprintf(`# Generated by mygrok task -- safe to edit.
# One container, all tunnels (tunnels.json). Logs: docker compose -f %s logs -f
name: mygrok-%s

services:
  mygrok:
    image: mygrok:${MYGROK_TAG:-%s}
    container_name: mygrok_%s
    command: ["mygrok", "up", "--config", "/etc/mygrok/tunnels.json", "--no-tui", "--log-format", "json"]
    environment:
      MYGROK_SERVER: ${MYGROK_SERVER}
      MYGROK_TOKEN: ${MYGROK_TOKEN}
    volumes:
      - ./tunnels.json:/etc/mygrok/tunnels.json:ro
%s`, composePath, name, tag, name, netBlock)
}

// runMultiAdd implements `add --multi`: the first run scaffolds
// <dir>/mygrok/{tunnels.json,docker-compose.yml,.env}; later runs append the
// new tunnel spec to tunnels.json (the compose file is left untouched, and
// .env is only recreated if it was deleted).
func runMultiAdd(p multiAddParams) error {
	if p.port <= 0 {
		return fmt.Errorf("--port is required")
	}
	if !isValidLabel(p.sub) {
		return fmt.Errorf("--sub must be a lowercase dns label (letters, digits, hyphens), got %q", p.sub)
	}
	if p.proto != "http" && p.proto != "https" && p.proto != "tcp" && p.proto != "udp" {
		return fmt.Errorf("--proto must be http|https|tcp|udp")
	}
	if p.network != "" && p.localHost == "127.0.0.1" {
		return fmt.Errorf("--network requires --local-host (the target container/service name on that network)")
	}

	mygrokDir := filepath.Join(p.dir, "mygrok")
	composePath := filepath.Join(mygrokDir, "docker-compose.yml")
	tunnelsPath := filepath.Join(mygrokDir, "tunnels.json")
	envPath := filepath.Join(mygrokDir, ".env")

	if err := guardMultiAdd(mygrokDir); err != nil {
		return err
	}
	fresh := !fileExists(tunnelsPath)
	cfg, err := loadMultiConfig(tunnelsPath)
	if err != nil {
		return err
	}
	for _, t := range cfg.Tunnels {
		if t.Subdomain == p.sub {
			return fmt.Errorf("subdomain %q is already in %s (pick a different --sub)", p.sub, tunnelsPath)
		}
	}

	spec := multiTunnelSpec{
		Name:       p.sub,
		Protocol:   p.proto,
		Port:       p.port,
		Subdomain:  p.sub,
		PublicPort: p.publicPort,
	}
	if p.localHost != "" && p.localHost != "127.0.0.1" {
		spec.LocalHost = p.localHost
	}
	cfg.Tunnels = append(cfg.Tunnels, spec)

	if err := os.MkdirAll(mygrokDir, 0o755); err != nil {
		return err
	}
	if err := saveMultiConfig(tunnelsPath, cfg); err != nil {
		return err
	}
	if !fileExists(envPath) {
		if err := os.WriteFile(envPath, []byte(envFileContent(p.server, p.token, p.tag)), 0o600); err != nil {
			return err
		}
	}
	if !fileExists(composePath) {
		name := sanitizeLabel(filepath.Base(p.dir))
		if err := os.WriteFile(composePath, []byte(multiComposeYAML(composePath, name, p.tag, p.network)), 0o644); err != nil {
			return err
		}
	}

	if fresh {
		fmt.Printf("Created %s/{tunnels.json,docker-compose.yml,.env}\n", mygrokDir)
		fmt.Printf("Start:  mygrok-task up %s\n", p.dir)
	} else {
		fmt.Printf("Added %s to %s\n", p.sub, tunnelsPath)
		fmt.Printf("Restart: mygrok-task down %s && mygrok-task up %s\n", p.dir, p.dir)
	}
	return nil
}

func isValidLabel(s string) bool {
	if s == "" || len(s) > 63 {
		return false
	}
	for i, r := range s {
		digit := r >= '0' && r <= '9'
		lower := r >= 'a' && r <= 'z'
		hype := r == '-'
		if !digit && !lower && !hype {
			return false
		}
		if (i == 0 || i == len(s)-1) && hype {
			return false
		}
	}
	return true
}

func composeDir(dirArg string) (string, error) {
	dir, err := filepath.Abs(dirArg)
	if err != nil || !isDir(dir) {
		return "", fmt.Errorf("directory not found: %s", dirArg)
	}
	p := filepath.Join(dir, "mygrok", "docker-compose.yml")
	if _, err := os.Stat(p); err != nil {
		return "", fmt.Errorf("no mygrok/ in %s (run: mygrok-task add %s --port <n> --sub <name>)", dir, dir)
	}
	return p, nil
}

func runDocker(composePath string, args ...string) error {
	cmd := exec.Command("docker", append([]string{"compose", "-f", composePath}, args...)...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	return cmd.Run()
}

func lifecycle(name string) *cobra.Command {
	return &cobra.Command{
		Use:   name + " <dir>",
		Short: name + " the mygrok tunnel of <dir>",
		Args:  cobra.RangeArgs(1, 2),
		RunE: func(cmd *cobra.Command, args []string) error {
			composePath, err := composeDir(args[0])
			if err != nil {
				return err
			}
			switch name {
			case "up":
				return runDocker(composePath, "up", "-d")
			case "down":
				return runDocker(composePath, "down")
			case "status":
				return runDocker(composePath, "ps")
			case "logs":
				a := []string{"logs", "-f", "--tail", "100"}
				if len(args) > 1 {
					a = append(a, args[1])
				}
				return runDocker(composePath, a...)
			}
			return nil
		},
	}
}

func configPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "mygrok", "env")
}

func readConfigFile() map[string]string {
	m := map[string]string{}
	data, err := os.ReadFile(configPath())
	if err != nil {
		return m
	}
	sc := bufio.NewScanner(strings.NewReader(string(data)))
	for sc.Scan() {
		if k, v, ok := strings.Cut(sc.Text(), "="); ok && strings.TrimSpace(k) != "" {
			m[strings.TrimSpace(k)] = strings.TrimSpace(v)
		}
	}
	return m
}

func writeConfigFile(m map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(configPath()), 0o700); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# mygrok task configuration -- keep secret (mode 0600).\n")
	for _, k := range []string{"MYGROK_SERVER", "MYGROK_TOKEN", "MYGROK_TAG"} {
		if v, ok := m[k]; ok && v != "" {
			fmt.Fprintf(&b, "%s=%s\n", k, v)
		}
	}
	return os.WriteFile(configPath(), []byte(b.String()), 0o600)
}

func prompt(line string) string {
	fmt.Print(line)
	var v string
	fmt.Scanln(&v)
	return strings.TrimSpace(v)
}

var configCmd = &cobra.Command{
	Use:   "config [set]",
	Short: "Show or edit ~/.config/mygrok/env (server address, token, image tag)",
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		m := readConfigFile()
		if len(args) > 0 && args[0] != "set" {
			return fmt.Errorf("unknown argument %q (use: task config [set])", args[0])
		}
		if len(args) == 1 {
			if v := flagServer; v != "" {
				m["MYGROK_SERVER"] = v
			} else if m["MYGROK_SERVER"] == "" {
				m["MYGROK_SERVER"] = prompt("MYGROK_SERVER (host:port): ")
			}
			if v := flagToken; v != "" {
				m["MYGROK_TOKEN"] = v
			} else if m["MYGROK_TOKEN"] == "" {
				m["MYGROK_TOKEN"] = prompt("MYGROK_TOKEN: ")
			}
			if v := flagImage; v != "" {
				m["MYGROK_TAG"] = v
			} else if m["MYGROK_TAG"] == "" {
				m["MYGROK_TAG"] = prompt("MYGROK_TAG [latest]: ")
				if m["MYGROK_TAG"] == "" {
					m["MYGROK_TAG"] = "latest"
				}
			}
			if m["MYGROK_SERVER"] == "" || m["MYGROK_TOKEN"] == "" {
				return fmt.Errorf("MYGROK_SERVER and MYGROK_TOKEN are required")
			}
			if err := writeConfigFile(m); err != nil {
				return err
			}
			fmt.Printf("Saved %s\n", configPath())
			return nil
		}
		fmt.Printf("Config file: %s\n", configPath())
		if m["MYGROK_SERVER"] == "" && m["MYGROK_TOKEN"] == "" {
			fmt.Println("(empty -- run: task config set)")
			return nil
		}
		fmt.Printf("  MYGROK_SERVER=%s\n", m["MYGROK_SERVER"])
		if m["MYGROK_TOKEN"] != "" {
			fmt.Printf("  MYGROK_TOKEN=%s...\n", m["MYGROK_TOKEN"][:min(4, len(m["MYGROK_TOKEN"]))])
		}
		fmt.Printf("  MYGROK_TAG=%s\n", m["MYGROK_TAG"])
		return nil
	},
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func main() {
	root := &cobra.Command{
		Use:           "mygrok-task",
		Short:         "mygrok tunnel manager: scaffold and run per-project docker compose tunnels",
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	root.PersistentFlags().StringVar(&flagServer, "server", "", "mygrok server address (overrides MYGROK_SERVER / ~/.config/mygrok/env)")
	root.PersistentFlags().StringVar(&flagToken, "token", "", "authentication token (overrides MYGROK_TOKEN / ~/.config/mygrok/env)")
	root.PersistentFlags().StringVar(&flagImage, "image", "", "mygrok image tag (overrides MYGROK_TAG, default: latest)")

	addCmd.Flags().Int("port", 0, "local port to expose (required)")
	addCmd.Flags().String("sub", "", "tunnel subdomain (required)")
	addCmd.Flags().Bool("multi", false, "multi-tunnel mode: one container runs all tunnels added to <dir> (later adds append to tunnels.json)")
	addCmd.Flags().String("proto", "http", "tunnel protocol: http|https|tcp|udp")
	addCmd.Flags().String("local-host", "127.0.0.1", "upstream host (use the container name with --network)")
	addCmd.Flags().String("network", "", "external docker network to join instead of network_mode: host")
	addCmd.Flags().Int("public-port", 0, "requested public port for tcp/udp (0 = auto)")

	root.AddCommand(addCmd, configCmd, lifecycle("up"), lifecycle("down"), lifecycle("status"), lifecycle("logs"))
	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		os.Exit(1)
	}
}
