package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/spf13/cobra"
)

var (
	flagServer string
	flagToken  string
	flagImage  string
)

// resolveSetting returns the first non-empty of: explicit flag, environment,
// ~/.config/mygrok/env (KEY=VALUE lines).
func resolveSetting(flagVal, envKey string) string {
	if flagVal != "" {
		return flagVal
	}
	if v := os.Getenv(envKey); v != "" {
		return v
	}
	if home, err := os.UserHomeDir(); err == nil {
		data, err := os.ReadFile(filepath.Join(home, ".config", "mygrok", "env"))
		if err == nil {
			sc := bufio.NewScanner(strings.NewReader(string(data)))
			for sc.Scan() {
				k, v, ok := strings.Cut(sc.Text(), "=")
				if ok && strings.TrimSpace(k) == envKey {
					return strings.TrimSpace(v)
				}
			}
		}
	}
	return ""
}

func requireServerToken() (string, string) {
	server := resolveSetting(flagServer, "MYGROK_SERVER")
	token := resolveSetting(flagToken, "MYGROK_TOKEN")
	if server == "" || token == "" {
		fmt.Fprintln(os.Stderr, "ERROR: MYGROK_SERVER / MYGROK_TOKEN not set.")
		fmt.Fprintln(os.Stderr, "Set them in the environment or in ~/.config/mygrok/env, e.g.:")
		fmt.Fprintln(os.Stderr, "  MYGROK_SERVER=your-vps.com:7000")
		fmt.Fprintln(os.Stderr, "  MYGROK_TOKEN=your-secret-token")
		os.Exit(1)
	}
	return server, token
}

func imageTag() string {
	if tag := resolveSetting(flagImage, "MYGROK_TAG"); tag != "" {
		return tag
	}
	return "latest"
}

var addCmd = &cobra.Command{
	Use:   "add <dir> --port <n> --sub <name>",
	Short: "Scaffold <dir>/mygrok/ with a docker-compose tunnel config",
	Long: `Scaffold a per-project mygrok tunnel: creates <dir>/mygrok/docker-compose.yml
(one tunnel = one container) and <dir>/mygrok/.env (server address + token,
mode 0600).

Examples:
  task add ~/dev/myapp --port 3000 --sub my-app
  task add ~/dev/mygame --port 8123 --sub mygame --network proxy --local-host mygame
  task add ~/dev/mybox --proto tcp --port 22 --sub ssh --public-port 2222`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		dir, err := filepath.Abs(args[0])
		if err != nil || !isDir(dir) {
			return fmt.Errorf("directory not found: %s", args[0])
		}
		server, token := requireServerToken()
		tag := imageTag()

		port, _ := cmd.Flags().GetInt("port")
		sub, _ := cmd.Flags().GetString("sub")
		proto, _ := cmd.Flags().GetString("proto")
		scheme, _ := cmd.Flags().GetString("scheme")
		localHost, _ := cmd.Flags().GetString("local-host")
		network, _ := cmd.Flags().GetString("network")
		publicPort, _ := cmd.Flags().GetInt("public-port")

		if port <= 0 {
			return fmt.Errorf("--port is required")
		}
		if !isValidLabel(sub) {
			return fmt.Errorf("--sub must be a lowercase dns label (letters, digits, hyphens), got %q", sub)
		}
		if proto != "http" && proto != "https" && proto != "tcp" && proto != "udp" {
			return fmt.Errorf("--proto must be http|https|tcp|udp")
		}
		if network != "" && localHost == "127.0.0.1" {
			return fmt.Errorf("--network requires --local-host (the target container/service name on that network)")
		}

		mygrokDir := filepath.Join(dir, "mygrok")
		composePath := filepath.Join(mygrokDir, "docker-compose.yml")
		if _, err := os.Stat(composePath); err == nil {
			return fmt.Errorf("%s already exists (refusing to overwrite; edit it or remove the folder)", composePath)
		}
		if err := os.MkdirAll(mygrokDir, 0o755); err != nil {
			return err
		}

		envContent := fmt.Sprintf("# Generated by mygrok task -- safe to edit.\nMYGROK_SERVER=%s\nMYGROK_TOKEN=%s\nMYGROK_TAG=%s\n", server, token, tag)
		if err := os.WriteFile(filepath.Join(mygrokDir, ".env"), []byte(envContent), 0o600); err != nil {
			return err
		}

		cmdArgs := []string{
			"mygrok", proto, strconv.Itoa(port), sub,
			"--server", "${MYGROK_SERVER}",
			"--no-tui", "--log-format", "json",
			"--local-host", localHost,
		}
		if scheme == "https" {
			cmdArgs = append(cmdArgs, "--insecure")
		}
		if publicPort > 0 {
			cmdArgs = append(cmdArgs, "--public-port", strconv.Itoa(publicPort))
		}
		var b strings.Builder
		b.WriteString("[")
		for i, a := range cmdArgs {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(`"` + a + `"`)
		}
		b.WriteString("]")

		var netBlock string
		if network != "" {
			netBlock = fmt.Sprintf("    networks:\n      - %s\n    restart: unless-stopped\n\nnetworks:\n  %s:\n    external: true\n", network, network)
		} else {
			netBlock = "    network_mode: host\n    restart: unless-stopped\n"
		}

		compose := fmt.Sprintf(`# Generated by mygrok task -- safe to edit.
# One tunnel = one container. Logs: docker compose -f %s logs -f
name: mygrok-%s

services:
  %s:
    image: mygrok:${MYGROK_TAG:-%s}
    container_name: mygrok_%s
    command: %s
    environment:
      MYGROK_TOKEN: ${MYGROK_TOKEN}
%s`, composePath, sub, sub, tag, sub, b.String(), netBlock)

		if err := os.WriteFile(composePath, []byte(compose), 0o644); err != nil {
			return err
		}
		fmt.Printf("Created %s/{docker-compose.yml,.env}\n", mygrokDir)
		fmt.Printf("Start:  mgrok-task up %s\n", dir)
		return nil
	},
}

func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func isValidLabel(s string) bool {
	if s == "" || len(s) > 63 {
		return false
	}
	for i, r := range s {
		digit := r >= '0' && r <= '9'
		lower := r >= 'a' && r <= 'z'
		hype := r == '-'
		if !digit && !lower && !hype {
			return false
		}
		if (i == 0 || i == len(s)-1) && hype {
			return false
		}
	}
	return true
}

func composeDir(dirArg string) (string, error) {
	dir, err := filepath.Abs(dirArg)
	if err != nil || !isDir(dir) {
		return "", fmt.Errorf("directory not found: %s", dirArg)
	}
	p := filepath.Join(dir, "mygrok", "docker-compose.yml")
	if _, err := os.Stat(p); err != nil {
		return "", fmt.Errorf("no mygrok/ in %s (run: mgrok-task add %s --port <n> --sub <name>)", dir, dir)
	}
	return p, nil
}

func runDocker(composePath string, args ...string) error {
	cmd := exec.Command("docker", append([]string{"compose", "-f", composePath}, args...)...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	return cmd.Run()
}

func lifecycle(name string) *cobra.Command {
	return &cobra.Command{
		Use:   name + " <dir>",
		Short: name + " the mygrok tunnel of <dir>",
		Args:  cobra.RangeArgs(1, 2),
		RunE: func(cmd *cobra.Command, args []string) error {
			composePath, err := composeDir(args[0])
			if err != nil {
				return err
			}
			switch name {
			case "up":
				return runDocker(composePath, "up", "-d")
			case "down":
				return runDocker(composePath, "down")
			case "status":
				return runDocker(composePath, "ps")
			case "logs":
				a := []string{"logs", "-f", "--tail", "100"}
				if len(args) > 1 {
					a = append(a, args[1])
				}
				return runDocker(composePath, a...)
			}
			return nil
		},
	}
}

func configPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "mygrok", "env")
}

func readConfigFile() map[string]string {
	m := map[string]string{}
	data, err := os.ReadFile(configPath())
	if err != nil {
		return m
	}
	sc := bufio.NewScanner(strings.NewReader(string(data)))
	for sc.Scan() {
		if k, v, ok := strings.Cut(sc.Text(), "="); ok && strings.TrimSpace(k) != "" {
			m[strings.TrimSpace(k)] = strings.TrimSpace(v)
		}
	}
	return m
}

func writeConfigFile(m map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(configPath()), 0o700); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# mygrok task configuration -- keep secret (mode 0600).\n")
	for _, k := range []string{"MYGROK_SERVER", "MYGROK_TOKEN", "MYGROK_TAG"} {
		if v, ok := m[k]; ok && v != "" {
			fmt.Fprintf(&b, "%s=%s\n", k, v)
		}
	}
	return os.WriteFile(configPath(), []byte(b.String()), 0o600)
}

func prompt(line string) string {
	fmt.Print(line)
	var v string
	fmt.Scanln(&v)
	return strings.TrimSpace(v)
}

var configCmd = &cobra.Command{
	Use:   "config [set]",
	Short: "Show or edit ~/.config/mygrok/env (server address, token, image tag)",
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		m := readConfigFile()
		if len(args) > 0 && args[0] != "set" {
			return fmt.Errorf("unknown argument %q (use: task config [set])", args[0])
		}
		if len(args) == 1 {
			if v := flagServer; v != "" {
				m["MYGROK_SERVER"] = v
			} else if m["MYGROK_SERVER"] == "" {
				m["MYGROK_SERVER"] = prompt("MYGROK_SERVER (host:port): ")
			}
			if v := flagToken; v != "" {
				m["MYGROK_TOKEN"] = v
			} else if m["MYGROK_TOKEN"] == "" {
				m["MYGROK_TOKEN"] = prompt("MYGROK_TOKEN: ")
			}
			if v := flagImage; v != "" {
				m["MYGROK_TAG"] = v
			} else if m["MYGROK_TAG"] == "" {
				m["MYGROK_TAG"] = prompt("MYGROK_TAG [latest]: ")
				if m["MYGROK_TAG"] == "" {
					m["MYGROK_TAG"] = "latest"
				}
			}
			if m["MYGROK_SERVER"] == "" || m["MYGROK_TOKEN"] == "" {
				return fmt.Errorf("MYGROK_SERVER and MYGROK_TOKEN are required")
			}
			if err := writeConfigFile(m); err != nil {
				return err
			}
			fmt.Printf("Saved %s\n", configPath())
			return nil
		}
		fmt.Printf("Config file: %s\n", configPath())
		if m["MYGROK_SERVER"] == "" && m["MYGROK_TOKEN"] == "" {
			fmt.Println("(empty -- run: task config set)")
			return nil
		}
		fmt.Printf("  MYGROK_SERVER=%s\n", m["MYGROK_SERVER"])
		if m["MYGROK_TOKEN"] != "" {
			fmt.Printf("  MYGROK_TOKEN=%s...\n", m["MYGROK_TOKEN"][:min(4, len(m["MYGROK_TOKEN"]))])
		}
		fmt.Printf("  MYGROK_TAG=%s\n", m["MYGROK_TAG"])
		return nil
	},
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func main() {
	root := &cobra.Command{
		Use:           "mgrok-task",
		Short:         "mygrok tunnel manager: scaffold and run per-project docker compose tunnels",
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	root.PersistentFlags().StringVar(&flagServer, "server", "", "mygrok server address (overrides MYGROK_SERVER / ~/.config/mygrok/env)")
	root.PersistentFlags().StringVar(&flagToken, "token", "", "authentication token (overrides MYGROK_TOKEN / ~/.config/mygrok/env)")
	root.PersistentFlags().StringVar(&flagImage, "image", "", "mygrok image tag (overrides MYGROK_TAG, default: latest)")

	addCmd.Flags().Int("port", 0, "local port to expose (required)")
	addCmd.Flags().String("sub", "", "tunnel subdomain (required)")
	addCmd.Flags().String("proto", "http", "tunnel protocol: http|https|tcp|udp")
	addCmd.Flags().String("scheme", "http", "local upstream scheme (http|https)")
	addCmd.Flags().String("local-host", "127.0.0.1", "upstream host (use the container name with --network)")
	addCmd.Flags().String("network", "", "external docker network to join instead of network_mode: host")
	addCmd.Flags().Int("public-port", 0, "requested public port for tcp/udp (0 = auto)")

	root.AddCommand(addCmd, configCmd, lifecycle("up"), lifecycle("down"), lifecycle("status"), lifecycle("logs"))
	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		os.Exit(1)
	}
}
